name: flutter_payoo_vn
description: This plugin helps in integrating the Payoo.vn native mobile SDK into Flutter application project.
version: 0.0.2
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: vn.payoo.flutter
        pluginClass: PayooVnPlugin
      ios:
        pluginClass: PayooVnPlugin